### ISSUE TITLE
ZRAM and SWAP not working together 

### ISSUE THREAD

**Issue by shevalier** [Linaro1985/padavan-fw#2]
If HDD contains SWAP, it mount first and when ZRAM create dev, OS not usage it.
cat /proc/swaps show only SWAP 
swapon -**s** - not implemented in Busybox

**Comment by Linaro1985** [comment]
Fixed in https://github.com/Linaro1985/padavan-fw/commit/42bad1766c2a8d59b7a962bf727d6198f9910fc6
