### ISSUE TITLE
Suggestion to rework dnscrypt-proxy

### ISSUE THREAD

**Issue by neuro18** [Linaro1985/padavan-fw#3]
Максим, добрый день.

Есть предложение немного переделать интеграцию dnscrypt в прошивке.

1. При подготовке ROMFS файл `dnscrypt-resolvers.csv` не копируется в `/usr/share/dnscrypt-proxy/`, т.к. в Makefile не отрабатывает строка `mkdir -p $(INSTALLDIR)/usr/share/dnscrypt-proxy` (не задана переменная `INSTALLDIR`).
Можно заменить создание директории и последующее копирование файла в нее одно командой: `$(ROMFSINST) -d dnscrypt-resolvers.csv /usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv` (опция -d создает все необходимые директории самостоятельно, не надо отдельных `mkdir`).

2. RC (через dnscrypt-proxy.sh) запускает dnscrypt-proxy с прибитыми гвоздями параметрами, взятыми из WebUI. На настоящий момент команда выглядит так: `/usr/sbin/dnscrypt-proxy --pidfile=/var/run/dnscrypt-proxy.pid --daemonize --resolver-name=${resolver} --local-address=${ipaddr}:${port}`

Предлагаю организовать передачу параметров через конфиг-файлы. Первый конфиг генерируется на лету (как это сделано во многих случаях у Падавана) в `/tmp/dnscrypt-proxy.conf` и наполняется параметрами, управляемыми из WebUI:
- `Имя резолвера` (из WebUI)
- `Локальный адрес` (из WebUI)
- `Локальный порт` (из WebUI)

плюс несколькими рабочими и/или неизменными:

- `Daemonize yes` (фиксированно)
- `PidFile /var/run/dnscrypt-proxy.pid` (фиксированно)
- `LogLevel 0` (**ДОБАВИТЬ** поле в WebUI для выбора пользователем, значение 0-7) (из WebUI)
- (**ОБЯЗАТЕЛЬНО!**) `Include /etc/storage/dnscrypt-proxy/dnscrypt-proxy.conf` (фиксированно)

Затем при запуске dnscrypt-proxy проверять наличие файла `/etc/storage/dnscrypt-proxy/dnscrypt-proxy.conf`, и если не найден, заполнять его из скрипта остальными параметрами по-умолчанию из [штатного файла настроек](https://raw.githubusercontent.com/Linaro1985/padavan-fw/rework/trunk/user/dnscrypt-proxy/dnscrypt-proxy-1.9.5/dnscrypt-proxy.conf), **МИНУС** те, что перечислены выше (которые кладутся в рантайме в файл `/tmp/dnscrypt-proxy.conf`). Таким образом все дополнительные параметры, недоступные из WebUI, пользователь может править вручную через терминал в `/etc/storage/dnscrypt-proxy/dnscrypt-proxy.conf`.

После всех этих изменений запускать dnscrypt-proxy не с прибитыми параметрами, а командой `/usr/sbin/dnscrypt-proxy /tmp/dnscypt-proxy.conf`

3. Интеграция с dnsmasq и iptables.

При запуске dnscrypt-proxy нужно добавить в dnsmasq.conf только две строчки:
- `no-resolv`
- `server=127.0.0.1#65053` (локальные адрес и порт из WebUI).

Опция `no-resolv` говорит dnsmasq не использовать для резолва сервера, полученные из WAN, а только прописанные в опции 'server' (т.е. только dnscrypt). Ваши опции `strict-order` и `except-interface=lo` не нужны.

Включение dnscrypt-proxy в WebUI корректнее было бы сделать просто Нет/Да, а не Нет/Да/Интеграция с dnsmasq/Интеграция с iptables.

Интеграцию с dnsmasq надо делать всегда, в этом смысл dnscrypt. Нет смысла пускать запросы одновременно через dnscrypt и через dns провайдера. Смысл защиты от спуфинга теряется. Dnscrypt, если включен, должен быть единственным резолвером. Если сервер dnscrypt вдруг отвалился, и у пользователя "пропал интернет", пользователь идет в WebUI и меняет резолвер или отключает dnscrypt, тем самым автоматически отключая опцию dnsmasq `no-resolv` и возвращаясь на DNS, полученные от провайдера.

В вашем исполнении Интеграция с dnsmasq и Интеграция с iptables взаимоисключающие. Их нельзя использовать одновременно. Хотя это как раз желательный вариант. Уберите поля Интеграция dnsmasq (делайте всегда) и Интеграция iptables, вместо которого добавьте чекбокс типа "Принудительно перенаправлять все DNS запросы клиентов в dnscrypt", при активации которого вы добавляете два правила в iptables:

`iptables -t nat -I PREROUTING -i br0 -p tcp --dport 53 -j DNAT --to $(nvram get lan_ipaddr)`
`iptables -t nat -I PREROUTING -i br0 -p udp --dport 53 -j DNAT --to $(nvram get lan_ipaddr)`

и удаляете при выключении dnscrypt или чекбокса.

4. Вы используете в dnscrypt-proxy.sh промежуточный файл `/tmp/dnscrypt-proxy.hash` для работы с параметрами. Зачем? Все они уже есть в nvram. Читайте его.

**Comment by neuro18** [comment]
Еще подумалось:

1. Если сделаете включение dnscrypt-proxy в WebUI только Нет/Да и чекбокс для iptables, то можно вообще перенести из скрипта `dnscrypt-proxy.sh` интеграцию c

- dnsmasq в `/rc/services_ex.c`, проверять (через nvram) включен ли dnscrypt и тогда добавлять параметры `no-resolv` и `server=$dnscryptlocaladdr:$dnscryptlocalport` прямо в `/etc/dnsmasq.conf`

- iptables в `/rc/firewall_ex.c`, проверять (через nvram) включен ли dnscrypt и включен ли чекбокс "Принуд. перенапр. запросы DNS в dnscrypt" и добавлять указанные правила iptables.

Там все более менее несложно, по аналогии с кодом в упомянутых файлах. Все это будет модифицировать нужные системные файлы в рантайме. Сейчас `dnscrypt-proxy.sh` модифицирует пользовательские скрипты в `/etc/storage`, что не совсем правильно, плюс дополнительно изнашивает флэш при перезаписи.

2. Если выполнить п.1, то в скрипте `dnscrypt-proxy.sh` можно оставить только создание основного файла конфигурации в `/etc/storage/dnscrypt-proxy/dnscrypt-proxy.conf`, если еще не существует, и запуск dnscrypt -- например с [таким содержимым](https://pastebin.com/8gCtKWrY).

Получается передача минимальных параметров при запуске, а остальные dnscrypt-proxy доберет из постоянного пользовательского конфига в `/etc/storage` (вроде dnscrypt скомпилирован с опцией  `--sysconfdir=/etc/storage/dnscrypt-proxy`, должен подцепить конфиг автоматом). И никакой возни с модификацией туда-обратно пользовательских скриптов и перезаписи флеша.

**Comment by Linaro1985** [comment]
Здравствуйте! Спасибо вам большое за развернутое описание недостатков и улучшений. Изначально поддержка TOR+dnscrypt+privoxy была реализована в виде патча для проекта rt-n56u, который находился в скрипте PROMETHEUS. Автором патча является пользователь qwe (http://4pda.ru/forum/index.php?showuser=2246952). Пользователи Freize и Developer_MZRIP с форума 4pda немного поправили патч (конкретно некоторые команды установки). Потом я его просто перенес в форк, поскольку у пользователей были проблемы со сборкой прошивки с использованием этого патча. Кое-какие мелкие недостатки я скорее всего поправлю в ближайшее время, но остальное потребует времени и внимательного изучения вопроса. С первым в последнее время сложности. В связи с этим есть два варианта:
1) Обратиться к автору патча.
2) Подождать пока у меня руки дойдут до этой переделки.

**Comment by neuro18** [comment]
Есть еще третий вариант. Я почти закончил вариант из второго сообщения, включая модификацию WebUI и rc. В ближайшие дни скину патч.

**Comment by Linaro1985** [comment]
Буду премного благодарен вам)

**Comment by Linaro1985** [comment]
Здравствуйте! Вы знаете, этот вопрос лучше задать в теме http://4pda.ru/forum/index.php?showtopic=714487

**Comment by Linaro1985** [comment]
@neuro18  А вообще, по-моему второй вариант самый оптимальный. Таким образом многое в WEBUI сделано.

**Comment by neuro18** [comment]
Сделал второй вариант. Параметры, как оказалось, в командной строке можно передать ВСЕ, включая использование плагинов. Которые все равно не собираются при текущих настройках (требуют дополнительную библиотеку).

Потратил кучу времени на понимание что есть что в сорцах :), и как все работает. Не осилил IPv6 (не использую), вернее не знаю, нужно ли что-то в этом плане добавлять при использовании dnscrypt. Так же не знаю как повлияет на отображение контролов TOR и Privoxy в WebUI (их не собираю). Надо будет кому-нибудь более опытному в прошивке Падавана посмотреть патч.

Только закончил, как вы добавили кучу коммитов, включая обновленный тулчейн. Блин :).

**Comment by neuro18** [comment]
Патч -- [rework_dnscrypt.zip](https://github.com/Linaro1985/padavan-fw/files/1959002/rework_dnscrypt.zip).

Особенности:

1. Не знаю как поведет себя с IPv6. Никогда не пользовался, ноль компетенций. Возможно что-то надо добавить в rc для этого дела. Делал для IPv4.

2. В прошу добавлен новый непривилегированный пользователь dnscrypt, под которым и работает процесс. Т.к. сервис сетевой, получает данные из инета, хз как там у него с защитой от взлома всякими переполнениями, отсутствием экранирования и пр. Не использовал уже существующий nobody потому, что [раз](https://unix.stackexchange.com/questions/272047/why-is-nobody-called-the-most-privileged-user-after-root) и [два](https://unix.stackexchange.com/questions/186568/what-is-nobody-user-and-group).

Как я и говорил, лучше бы еще кто-нибудь опытный посмотрел. Может где-то необходимо добавить дополнительные проверки всяких условий (например на работу роутера в различных режимах) и пр. В моей конфигурации работает прекрасно.

**Comment by Linaro1985** [comment]
Спасибо. Я посмотрю. Насчет, nobody. Не думаю, что с ним будут проблемы. Если все ok, то переправлю на него.

**Comment by spvkgn** [comment]
@neuro18 Возможно есть смысл сделать Pull request в апстрим, ранее там [писали](https://bitbucket.org/padavan/rt-n56u/issues/346/add-dnscrypt) что такой PR будет рассмотрен если сделать поддержку WebUI.

**Comment by neuro18** [comment]
Насчет пользователя dnscrypt: там всего 2 строчки кода :), на размер проши не влияет, пишет сразу в файлы passw и group. Под nobody уже работает dnsmasq, у некоторых еще и openvpn. Для SSH privilege separation, например, Падаван также делал отдельного пользователя. Впрочем, подумайте. Я ни разу не эксперт по Linux.

Pull request не умею, попробую разобраться.

**Comment by Linaro1985** [comment]
Нет смысла делать pull request на оригинальных исходниках. Там это никому не нужно по определенным причинам. Насчет nobody пользователя я внимательно изучу этот вопрос.

**Comment by Linaro1985** [comment]
Добавлено в исходники. Спасибо огромное за проделанную работу!
