### ISSUE TITLE
OpenVPN: Replace obsolete --ns-cert-type by --remote-cert-tls

### ISSUE THREAD

**Issue by dartraiden** [Linaro1985/padavan-fw#4]
Starting from OpenVPN v2.4, option [--ns-cert-type](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--ns-cert-type) is deprecated and throw warning:

`WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.`

We can do this manually, so as not to pollute syslog:
https://github.com/Linaro1985/padavan-fw/blob/master/trunk/user/rc/vpn_openvpn.c#L1074
https://github.com/Linaro1985/padavan-fw/blob/master/trunk/user/scripts/mtd_storage.sh#L559

**Comment by Linaro1985** [comment]
Done in this [commit](https://github.com/Linaro1985/padavan-fw/commit/1ae3f456eb3c705db6030ed34dfb60b883989c77).
